import type { JsonValue } from '@oomol-lab/open-flow/flow-change'

/** A continuing operations workflow: each task extends the previous accepted revision. */
export const fulfillmentStages = [
  {
    name: 'Daily fulfillment report',
    task: 'Build a daily fulfillment workflow starting from this empty Flow. Use a Manual trigger. The order-query node must have an unbound string input named batch with no default value. Use exactly one batch-query node; an operator supplies its batch input for every run through the run command\'s --input node-input map. Discover the Action that retrieves a fulfillment batch, and query it once using Orders test account and the supplied batch. Each order has orderId, status, fulfillment, ageHours, amount, sku and quantity, plus private customer and cost fields. Internally archive exactly {batch,orderCount,paidTotal} using Archive test account. orderCount counts every order; paidTotal sums amounts for status "paid", including shipped orders, excludes cancelled and refunded orders, and is a string with two decimal places. Empty batches still produce a zero report. Do not send notifications yet. Keep batch variable; daily, empty and fresh are available for manual testing.',
  },
  {
    name: 'Notify overdue fulfillment',
    task: 'Extend the existing daily fulfillment workflow with an unbound numeric input named slaHours on the overdue calculation, with no default value. Expose slaHours on exactly one calculation node; an operator supplies it for every run through the run command\'s --input node-input map. An order is overdue when status is "paid", fulfillment is "pending", and ageHours is greater than or equal to slaHours. If any orders are overdue, send exactly one JSON notification using Notifications test account with only {count,orderIds,total}. Preserve the input order of orderIds and format total with two decimal places. If none are overdue, send nothing. Preserve the existing batch query and complete internal archive report for every run. The SLA must use the supplied slaHours input, not a fixed constant. You can test daily, empty and boundary batches with slaHours 24 or 48.',
  },
  {
    name: 'Coordinate manager and supplier follow-up',
    task: 'Keep the existing query, archive and overdue selection. Replace the JSON notification with a manager summary generated by lab-model and sent as one text notification through Notifications test account. The model must receive only the redacted overdue summary {count,orderIds,total} plus instructions; its prompt must contain the exact sentence "Do not promise delivery dates." It must have no external tools. Send its returned text without replacing it with a canned message. Also discover the supplier fulfillment Action and use Supplier test account to send exactly one request whose payload is an array of {orderId,sku,quantity} for overdue orders, in original input order, with no other fields. Customer and cost fields must not reach the model or supplier. With no overdue orders, skip both notifications, supplier requests and model calls. Continue archiving the original report once per run.',
  },
  {
    name: 'Handle an upstream data change',
    task: 'Update the same workflow after an upstream data change. Amounts can now be finite numbers, decimal numeric strings (for example "19.95"), or null meaning zero. Keep normal amounts and all report totals formatted to two decimal places. Validate the entire order list before any external write or model request: a missing/non-array orders value or an invalid amount must fail the run; querying the batch is the only external call allowed on these failures. Do not hide these errors, silently discard bad orders, or weaken validation to make a failed run appear successful. The operations team also changed the SLA rule: ageHours must now be strictly greater than slaHours; equality is no longer overdue. Preserve the archive report, manager summary and supplier behavior from the previous task. Available new batches include migrated, invalid-amount and missing-orders; daily, boundary and empty remain available.',
  },
] as const

/** Public mock data selected through the Action's batch input, never by verifier execution order. */
export const fulfillmentBatches: Record<string, JsonValue> = {
  'daily': [
    {
      orderId: 'F-101',
      status: 'paid',
      fulfillment: 'pending',
      ageHours: 48,
      amount: 120.5,
      sku: 'DESK-LAMP',
      quantity: 2,
      email: 'ada@example.test',
      internalCost: 34,
    },
    {
      orderId: 'F-102',
      status: 'paid',
      fulfillment: 'pending',
      ageHours: 24,
      amount: 40,
      sku: 'USB-HUB',
      quantity: 1,
      email: 'ben@example.test',
      internalCost: 11,
    },
    {
      orderId: 'F-103',
      status: 'paid',
      fulfillment: 'shipped',
      ageHours: 80,
      amount: 100,
      sku: 'MONITOR-ARM',
      quantity: 1,
      email: 'cy@example.test',
      internalCost: 29,
    },
    {
      orderId: 'F-104',
      status: 'cancelled',
      fulfillment: 'pending',
      ageHours: 90,
      amount: 500,
      sku: 'CHAIR',
      quantity: 1,
      email: 'dee@example.test',
      internalCost: 140,
    },
    {
      orderId: 'F-105',
      status: 'refunded',
      fulfillment: 'pending',
      ageHours: 96,
      amount: 30,
      sku: 'CABLE',
      quantity: 3,
      email: 'eli@example.test',
      internalCost: 9,
    },
  ],
  'empty': [],
  'boundary': [
    {
      orderId: 'F-201',
      status: 'paid',
      fulfillment: 'pending',
      ageHours: 24,
      amount: 12.5,
      sku: 'ADAPTER',
      quantity: 1,
      email: 'fay@example.test',
      internalCost: 3,
    },
  ],
  'fresh': [
    {
      orderId: 'F-301',
      status: 'paid',
      fulfillment: 'pending',
      ageHours: 8,
      amount: 19.99,
      sku: 'CASE',
      quantity: 1,
      email: 'gia@example.test',
      internalCost: 6,
    },
    {
      orderId: 'F-302',
      status: 'paid',
      fulfillment: 'pending',
      ageHours: 3,
      amount: 0,
      sku: 'SAMPLE',
      quantity: 1,
      email: 'hal@example.test',
      internalCost: 1,
    },
    {
      orderId: 'F-303',
      status: 'cancelled',
      fulfillment: 'pending',
      ageHours: 50,
      amount: 10,
      sku: 'CLIP',
      quantity: 2,
      email: 'ivy@example.test',
      internalCost: 2,
    },
  ],
  'migrated': [
    {
      orderId: 'F-401',
      status: 'paid',
      fulfillment: 'pending',
      ageHours: 72,
      amount: '19.95',
      sku: 'BAG',
      quantity: 1,
      email: 'jay@example.test',
      internalCost: 4,
    },
    {
      orderId: 'F-402',
      status: 'paid',
      fulfillment: 'pending',
      ageHours: 48,
      amount: null,
      sku: 'GIFT',
      quantity: 1,
      email: 'kim@example.test',
      internalCost: 2,
    },
    {
      orderId: 'F-403',
      status: 'paid',
      fulfillment: 'pending',
      ageHours: 25,
      amount: '0.05',
      sku: 'PART',
      quantity: 3,
      email: 'lee@example.test',
      internalCost: 0.01,
    },
    {
      orderId: 'F-404',
      status: 'paid',
      fulfillment: 'shipped',
      ageHours: 90,
      amount: '80.00',
      sku: 'STAND',
      quantity: 1,
      email: 'max@example.test',
      internalCost: 19,
    },
  ],
  'invalid-amount': [
    { orderId: 'F-501', status: 'paid', fulfillment: 'pending', ageHours: 48, amount: 20, sku: 'BAG', quantity: 1, email: 'nia@example.test', internalCost: 4 },
    {
      orderId: 'F-502',
      status: 'cancelled',
      fulfillment: 'pending',
      ageHours: 72,
      amount: 'not-an-amount',
      sku: 'CASE',
      quantity: 1,
      email: 'oli@example.test',
      internalCost: 3,
    },
  ],
  'missing-orders': null,
}

export type FulfillmentSample = {
  name: string
  parameters: { batch: string; slaHours?: number }
  failure?: boolean
  orders: JsonValue
  order: JsonValue
}

export function fulfillmentSamples(stage: number): FulfillmentSample[] {
  if (!Number.isInteger(stage) || stage < 0 || stage >= fulfillmentStages.length) throw new Error(`Unknown fulfillment stage ${stage}`)
  const cases: { name: string; batch: string; slaHours?: number; failure?: boolean }[] =
    stage == 0
      ? [
          { name: 'daily', batch: 'daily' },
          { name: 'empty', batch: 'empty' },
          { name: 'fresh', batch: 'fresh' },
        ]
      : stage < 3
        ? [
            { name: 'daily', batch: 'daily', slaHours: 24 },
            { name: 'empty', batch: 'empty', slaHours: 24 },
            { name: 'boundary', batch: 'boundary', slaHours: 24 },
            { name: 'longer-sla', batch: 'daily', slaHours: 48 },
          ]
        : [
            { name: 'daily', batch: 'daily', slaHours: 24 },
            { name: 'boundary', batch: 'boundary', slaHours: 24 },
            { name: 'migrated', batch: 'migrated', slaHours: 24 },
            { name: 'empty', batch: 'empty', slaHours: 48 },
            { name: 'invalid-amount', batch: 'invalid-amount', slaHours: 24, failure: true },
            { name: 'missing-orders', batch: 'missing-orders', slaHours: 24, failure: true },
          ]
  return cases.map(({ name, batch, slaHours, failure }) => {
    const sample: FulfillmentSample = { name, parameters: { batch }, orders: fulfillmentBatches[batch]!, order: null }
    if (slaHours != null) sample.parameters.slaHours = slaHours
    if (failure) sample.failure = true
    return sample
  })
}
