import type { UiLanguage } from '../../localization/common/languages.ts'

export const triggerConfigFieldLabels: Readonly<Record<UiLanguage, Readonly<Record<string, Readonly<Record<string, string>>>>>> = {
  'en': {
    'feishu_app_bot.on_event': { sourceId: 'Event source', eventTypes: 'Events to receive' },
    'airtable.on_record_changed': { baseId: 'Base', tableIdOrName: 'Table', triggerField: 'Trigger field' },
    'github.on_repo_event': { events: 'Events', owner: 'Repository owner', repo: 'Repository' },
    'github.watch_pull_request': { owner: 'Repository owner', repo: 'Repository', number: 'Pull request number' },
    'gitlab.on_project_event': { events: 'Events', project: 'Project' },
    'googlecalendar.on_event_changed': { calendarId: 'Calendar' },
    'googledrive.on_file_change': { changeType: 'Change type', folderId: 'Folder' },
    'googlesheets.on_row_added': { sheet: 'Worksheet', spreadsheetId: 'Spreadsheet' },
    'linear.on_issue_changed': { teamId: 'Team' },
    'notion.on_database_page_event': { databaseId: 'Database' },
    'shopify.on_shop_event': { topics: 'Topics' },
    'slack.on_message_posted': { channelId: 'Channel' },
    'stripe.on_event': { events: 'Events' },
    'telegram.on_update': { updates: 'Updates' },
    'woocommerce.on_store_event': { events: 'Events' },
    'zendesk.on_event': { events: 'Events' },
  },
  'zh-CN': {
    'feishu_app_bot.on_event': { sourceId: '事件源', eventTypes: '接收的事件' },
    'airtable.on_record_changed': { baseId: 'Base', tableIdOrName: '数据表', triggerField: '触发字段' },
    'github.on_repo_event': { events: '事件', owner: '仓库所有者', repo: '仓库' },
    'github.watch_pull_request': { owner: '仓库所有者', repo: '仓库', number: '拉取请求编号' },
    'gitlab.on_project_event': { events: '事件', project: '项目' },
    'googlecalendar.on_event_changed': { calendarId: '日历' },
    'googledrive.on_file_change': { changeType: '变更类型', folderId: '文件夹' },
    'googlesheets.on_row_added': { sheet: '工作表', spreadsheetId: '电子表格' },
    'linear.on_issue_changed': { teamId: '团队' },
    'notion.on_database_page_event': { databaseId: '数据库' },
    'shopify.on_shop_event': { topics: '主题' },
    'slack.on_message_posted': { channelId: '频道' },
    'stripe.on_event': { events: '事件' },
    'telegram.on_update': { updates: '更新类型' },
    'woocommerce.on_store_event': { events: '事件' },
    'zendesk.on_event': { events: '事件' },
  },
  'zh-TW': {
    'feishu_app_bot.on_event': { sourceId: '事件來源', eventTypes: '接收的事件' },
    'airtable.on_record_changed': { baseId: 'Base', tableIdOrName: '資料表', triggerField: '觸發欄位' },
    'github.on_repo_event': { events: '事件', owner: '儲存庫擁有者', repo: '儲存庫' },
    'github.watch_pull_request': { owner: '儲存庫擁有者', repo: '儲存庫', number: '提取要求編號' },
    'gitlab.on_project_event': { events: '事件', project: '專案' },
    'googlecalendar.on_event_changed': { calendarId: '日曆' },
    'googledrive.on_file_change': { changeType: '變更類型', folderId: '資料夾' },
    'googlesheets.on_row_added': { sheet: '工作表', spreadsheetId: '試算表' },
    'linear.on_issue_changed': { teamId: '團隊' },
    'notion.on_database_page_event': { databaseId: '資料庫' },
    'shopify.on_shop_event': { topics: '主題' },
    'slack.on_message_posted': { channelId: '頻道' },
    'stripe.on_event': { events: '事件' },
    'telegram.on_update': { updates: '更新類型' },
    'woocommerce.on_store_event': { events: '事件' },
    'zendesk.on_event': { events: '事件' },
  },
  'ja': {
    'feishu_app_bot.on_event': { sourceId: 'イベントソース', eventTypes: '受信するイベント' },
    'airtable.on_record_changed': { baseId: 'ベース', tableIdOrName: 'テーブル', triggerField: 'トリガーフィールド' },
    'github.on_repo_event': { events: 'イベント', owner: 'リポジトリの所有者', repo: 'リポジトリ' },
    'github.watch_pull_request': { owner: 'リポジトリの所有者', repo: 'リポジトリ', number: 'プルリクエスト番号' },
    'gitlab.on_project_event': { events: 'イベント', project: 'プロジェクト' },
    'googlecalendar.on_event_changed': { calendarId: 'カレンダー' },
    'googledrive.on_file_change': { changeType: '変更の種類', folderId: 'フォルダー' },
    'googlesheets.on_row_added': { sheet: 'シート', spreadsheetId: 'スプレッドシート' },
    'linear.on_issue_changed': { teamId: 'チーム' },
    'notion.on_database_page_event': { databaseId: 'データベース' },
    'shopify.on_shop_event': { topics: 'トピック' },
    'slack.on_message_posted': { channelId: 'チャンネル' },
    'stripe.on_event': { events: 'イベント' },
    'telegram.on_update': { updates: '更新の種類' },
    'woocommerce.on_store_event': { events: 'イベント' },
    'zendesk.on_event': { events: 'イベント' },
  },
  'ko': {
    'feishu_app_bot.on_event': { sourceId: '이벤트 소스', eventTypes: '수신할 이벤트' },
    'airtable.on_record_changed': { baseId: '베이스', tableIdOrName: '테이블', triggerField: '트리거 필드' },
    'github.on_repo_event': { events: '이벤트', owner: '저장소 소유자', repo: '저장소' },
    'github.watch_pull_request': { owner: '저장소 소유자', repo: '저장소', number: '풀 리퀘스트 번호' },
    'gitlab.on_project_event': { events: '이벤트', project: '프로젝트' },
    'googlecalendar.on_event_changed': { calendarId: '캘린더' },
    'googledrive.on_file_change': { changeType: '변경 유형', folderId: '폴더' },
    'googlesheets.on_row_added': { sheet: '시트', spreadsheetId: '스프레드시트' },
    'linear.on_issue_changed': { teamId: '팀' },
    'notion.on_database_page_event': { databaseId: '데이터베이스' },
    'shopify.on_shop_event': { topics: '주제' },
    'slack.on_message_posted': { channelId: '채널' },
    'stripe.on_event': { events: '이벤트' },
    'telegram.on_update': { updates: '업데이트 유형' },
    'woocommerce.on_store_event': { events: '이벤트' },
    'zendesk.on_event': { events: '이벤트' },
  },
  'ru': {
    'feishu_app_bot.on_event': { sourceId: 'Источник событий', eventTypes: 'Принимаемые события' },
    'airtable.on_record_changed': { baseId: 'База', tableIdOrName: 'Таблица', triggerField: 'Поле триггера' },
    'github.on_repo_event': { events: 'События', owner: 'Владелец репозитория', repo: 'Репозиторий' },
    'github.watch_pull_request': { owner: 'Владелец репозитория', repo: 'Репозиторий', number: 'Номер запроса на слияние' },
    'gitlab.on_project_event': { events: 'События', project: 'Проект' },
    'googlecalendar.on_event_changed': { calendarId: 'Календарь' },
    'googledrive.on_file_change': { changeType: 'Тип изменения', folderId: 'Папка' },
    'googlesheets.on_row_added': { sheet: 'Лист', spreadsheetId: 'Таблица' },
    'linear.on_issue_changed': { teamId: 'Команда' },
    'notion.on_database_page_event': { databaseId: 'База данных' },
    'shopify.on_shop_event': { topics: 'Темы' },
    'slack.on_message_posted': { channelId: 'Канал' },
    'stripe.on_event': { events: 'События' },
    'telegram.on_update': { updates: 'Типы обновлений' },
    'woocommerce.on_store_event': { events: 'События' },
    'zendesk.on_event': { events: 'События' },
  },
  'fr': {
    'feishu_app_bot.on_event': { sourceId: 'Source d’événements', eventTypes: 'Événements à recevoir' },
    'airtable.on_record_changed': { baseId: 'Base', tableIdOrName: 'Table', triggerField: 'Champ déclencheur' },
    'github.on_repo_event': { events: 'Événements', owner: 'Propriétaire du dépôt', repo: 'Dépôt' },
    'github.watch_pull_request': { owner: 'Propriétaire du dépôt', repo: 'Dépôt', number: 'Numéro de la demande de tirage' },
    'gitlab.on_project_event': { events: 'Événements', project: 'Projet' },
    'googlecalendar.on_event_changed': { calendarId: 'Agenda' },
    'googledrive.on_file_change': { changeType: 'Type de modification', folderId: 'Dossier' },
    'googlesheets.on_row_added': { sheet: 'Feuille', spreadsheetId: 'Feuille de calcul' },
    'linear.on_issue_changed': { teamId: 'Équipe' },
    'notion.on_database_page_event': { databaseId: 'Base de données' },
    'shopify.on_shop_event': { topics: 'Sujets' },
    'slack.on_message_posted': { channelId: 'Canal' },
    'stripe.on_event': { events: 'Événements' },
    'telegram.on_update': { updates: 'Types de mise à jour' },
    'woocommerce.on_store_event': { events: 'Événements' },
    'zendesk.on_event': { events: 'Événements' },
  },
}
