// Generated by trigger-locales.ts. Do not edit; update provider locales/*.json instead.

import resource0 from '../airtable/locales/ko.json' with { type: 'json' }
import resource1 from '../github/locales/ko.json' with { type: 'json' }
import resource2 from '../gitlab/locales/ko.json' with { type: 'json' }
import resource3 from '../gmail/locales/ko.json' with { type: 'json' }
import resource4 from '../google-calendar/locales/ko.json' with { type: 'json' }
import resource5 from '../google-drive/locales/ko.json' with { type: 'json' }
import resource6 from '../google-sheets/locales/ko.json' with { type: 'json' }
import resource7 from '../linear/locales/ko.json' with { type: 'json' }
import resource8 from '../notion/locales/ko.json' with { type: 'json' }
import resource9 from '../one-drive/locales/ko.json' with { type: 'json' }
import resource10 from '../outlook/locales/ko.json' with { type: 'json' }
import resource11 from '../shopify/locales/ko.json' with { type: 'json' }
import resource12 from '../slack/locales/ko.json' with { type: 'json' }
import resource13 from '../stripe/locales/ko.json' with { type: 'json' }
import resource14 from '../telegram/locales/ko.json' with { type: 'json' }
import resource15 from '../woocommerce/locales/ko.json' with { type: 'json' }
import resource16 from '../zendesk/locales/ko.json' with { type: 'json' }

export default {
  ...resource0,
  ...resource1,
  ...resource2,
  ...resource3,
  ...resource4,
  ...resource5,
  ...resource6,
  ...resource7,
  ...resource8,
  ...resource9,
  ...resource10,
  ...resource11,
  ...resource12,
  ...resource13,
  ...resource14,
  ...resource15,
  ...resource16,
}
