export const controlErrorCode = {
  authenticationRequired: 'authentication.required',
  authorizationDenied: 'authorization.denied',
  bindingUnresolved: 'binding.unresolved',
  connectorActionNotFound: 'connector.action-not-found',
  connectorUnconfigured: 'connector.unconfigured',
  connectorUnavailable: 'connector.unavailable',
  engineUnavailable: 'engine.unavailable',
  engineUnsupported: 'engine.unsupported',
  flowInvalid: 'flow.invalid',
  flowNotFound: 'flow.not-found',
  flowBusy: 'flow.busy',
  flowConflict: 'flow.conflict',
  flowPresentationConflict: 'flow.presentation-conflict',
  flowRevisionConflict: 'flow.revision-conflict',
  liveConflict: 'live.conflict',
  liveNotFound: 'live.not-found',
  pageInvalidCursor: 'page.invalid-cursor',
  publicationConflict: 'publication.conflict',
  publicationNotFound: 'publication.not-found',
  publicationUnsupported: 'publication.unsupported',
  publishOperationNotFound: 'publication.operation-not-found',
  routeNotFound: 'route.not-found',
  runConflict: 'run.conflict',
  runEventsExpired: 'run.events-expired',
  runInvalid: 'run.invalid',
  runNotFound: 'run.not-found',
  runNotTerminal: 'run.not-terminal',
  runOverloaded: 'run.overloaded',
  runWaitNotFound: 'run.wait-not-found',
  triggerKeyInvalid: 'trigger-key.invalid',
  triggerKeyNotFound: 'trigger-key.not-found',
  triggerNotFound: 'trigger.not-found',
  variableInvalid: 'variable.invalid',
  variableLimitReached: 'variable.limit-reached',
  variableNotFound: 'variable.not-found',
} as const

export type ControlErrorCode = (typeof controlErrorCode)[keyof typeof controlErrorCode]

export const controlErrorMetadata = {
  [controlErrorCode.authenticationRequired]: { status: 401 },
  [controlErrorCode.authorizationDenied]: { status: 403 },
  [controlErrorCode.bindingUnresolved]: { status: 409 },
  [controlErrorCode.connectorActionNotFound]: { status: 404 },
  [controlErrorCode.connectorUnconfigured]: { status: 503 },
  [controlErrorCode.connectorUnavailable]: { status: 503 },
  [controlErrorCode.engineUnavailable]: { status: 503 },
  [controlErrorCode.engineUnsupported]: { status: 409 },
  [controlErrorCode.flowInvalid]: { status: 400 },
  [controlErrorCode.flowNotFound]: { status: 404 },
  [controlErrorCode.flowBusy]: { status: 409 },
  [controlErrorCode.flowConflict]: { status: 409 },
  [controlErrorCode.flowPresentationConflict]: { status: 412 },
  [controlErrorCode.flowRevisionConflict]: { status: 412 },
  [controlErrorCode.liveConflict]: { status: 412 },
  [controlErrorCode.liveNotFound]: { status: 404 },
  [controlErrorCode.pageInvalidCursor]: { status: 400 },
  [controlErrorCode.publicationConflict]: { status: 409 },
  [controlErrorCode.publicationNotFound]: { status: 404 },
  [controlErrorCode.publicationUnsupported]: { status: 409 },
  [controlErrorCode.publishOperationNotFound]: { status: 404 },
  [controlErrorCode.routeNotFound]: { status: 404 },
  [controlErrorCode.runConflict]: { status: 409 },
  [controlErrorCode.runEventsExpired]: { status: 410 },
  [controlErrorCode.runInvalid]: { status: 400 },
  [controlErrorCode.runNotFound]: { status: 404 },
  [controlErrorCode.runNotTerminal]: { status: 409 },
  [controlErrorCode.runOverloaded]: { status: 429 },
  [controlErrorCode.runWaitNotFound]: { status: 404 },
  [controlErrorCode.triggerKeyInvalid]: { status: 409 },
  [controlErrorCode.triggerKeyNotFound]: { status: 404 },
  [controlErrorCode.triggerNotFound]: { status: 404 },
  [controlErrorCode.variableInvalid]: { status: 400 },
  [controlErrorCode.variableLimitReached]: { status: 409 },
  [controlErrorCode.variableNotFound]: { status: 404 },
} as const satisfies Record<ControlErrorCode, { readonly status: number }>
